version: 2.1
jobs:
  run_test:
    docker:
      - image: circleci/node:14
<<<<<<< HEAD
      - image: mongo
      - image: redis
=======
>>>>>>> 6eee0cb744a86478deeefa9587c92fed35844213
    steps:
      - checkout
      - run:
          name: Install npm depenedncy
          command: npm install --save
      - run:
          name: Run unit test
          command: npm run test
workflows:
  build_test:
    jobs:
      - run_test
