version: 2.1
jobs:
  run_test:
    docker:
      - image: circleci/node:14
      - image: mongo
      - image: redis
    steps:
      - checkout
      - run:
          name: Install npm depenedncy
          command: npm install --save
      - run:
          name: Run unit test
          command: npm run test
workflows:
  build_test:
    jobs:
      - run_test